### ISSUE TITLE
Client makes multiple attempts to register service MSA, causing nonce errors

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/example-client-frequency#3]
Fix the hackiness where the Main component just keeps trying to register a service MSA repeatedly because it doesn't find one.

Repeated pallet_msa::create RPC requests return an error, which is displayed as a simple Javascript alert.  The alert is fine as an error for now, but we should send the RPC request only once, and show an error only if the initial one fails.

**Comment by wilwade** [comment]
Archive
