### ISSUE TITLE
Demo: On-chain Messaging version of Frequency via example-client-frequency

### ISSUE THREAD

**Issue by mehtaishita** [LibertyDSNP/example-client-frequency#5]
This demo should use example-client-frequency

As a developer using frequency and example-client-frequency, I should be able to send a message and see it presented in the block

1. Dev has frequency running locally (or devnet)
2. Dev connects example-client-frequency to that frequency instance
3. Dev can push a button to create a new hard coded Arvo on-chain schema
4. Dev can see a list of active schemas
    - Schema Id
    - Model Type
    - Payload Location
    - Decoded Model (Not the hex, but the JS object as JSON)
6. Dev can select an active on-chain schema and put in JSON that validates locally against the Arvo schema model
    - Alt: Put in field that allow you to build the message
    - Then validate
8. Dev can then submit the message to the chain (example-client-frequency does the Arvo serialization from the JSON)
    - ArvoBinary serialization should happen
10. Dev can then wait and see the call in Polkadot js
11. Dev can then request the messages for the same schema in example-client-frequency and see the Messages' JSON data (arvobinary -> parse with schema -> serialize to JSON)
    - Suggested`JSON.stringify(data, null, ' ');` for readablity

**Comment by wilwade** [comment]
Closed with #7
